# Generated by Django 3.1.7 on 2021-03-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('tfno', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
