# Generated by Django 3.1.6 on 2021-03-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('contrasenia', models.CharField(max_length=128, verbose_name='Passwd')),
                ('numero_cuenta', models.CharField(max_length=7, verbose_name='Numero de Cuenta')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('tipo_cuenta', models.CharField(max_length=10, verbose_name='Tipo de Cuenta')),
                ('saldo', models.FloatField(verbose_name='Saldo')),
                ('nombre_usuario', models.CharField(max_length=20, verbose_name='Nombre de Usuario')),
            ],
        ),
    ]
