# Generated by Django 3.1.6 on 2021-03-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balconServicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
