# Generated by Django 3.1.6 on 2021-03-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balconServicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('numero_transaccion', models.CharField(max_length=9, verbose_name='Numero Transaccion')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo transaccion')),
                ('concepto', models.CharField(max_length=64, verbose_name='Concepto del movimiento')),
                ('monto', models.FloatField(verbose_name='Monto del movimiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balconServicios.cuentas')),
            ],
        ),
    ]
